/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gdbfdiff (void)
{
  GtkWidget *window_gdbfdiff;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit_giconv;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *about_giconv;
  GtkWidget *frame_input;
  GtkWidget *alignment2;
  GtkWidget *filechooserbutton_input1;
  GtkWidget *label_input;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *filechooserbutton_input2;
  GtkWidget *label_input2;
  GtkWidget *hbuttonbox1;
  GtkWidget *button_cancel;
  GtkWidget *button_ok;
  GtkWidget *statusbar_gdbfdiff;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_gdbfdiff = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_gdbfdiff), _("gdbfdiff"));
  gtk_window_set_icon_name (GTK_WINDOW (window_gdbfdiff), "gtk-execute");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_gdbfdiff), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit_giconv = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit_giconv);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit_giconv);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  about_giconv = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about_giconv);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about_giconv);

  frame_input = gtk_frame_new (NULL);
  gtk_widget_show (frame_input);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_input, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_input), 4);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame_input), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  filechooserbutton_input1 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton_input1);
  gtk_container_add (GTK_CONTAINER (alignment2), filechooserbutton_input1);

  label_input = gtk_label_new (_("<b>Input 1</b>"));
  gtk_widget_show (label_input);
  gtk_frame_set_label_widget (GTK_FRAME (frame_input), label_input);
  gtk_label_set_use_markup (GTK_LABEL (label_input), TRUE);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 4);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  filechooserbutton_input2 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton_input2);
  gtk_container_add (GTK_CONTAINER (alignment1), filechooserbutton_input2);

  label_input2 = gtk_label_new (_("<b>Input 2</b>"));
  gtk_widget_show (label_input2);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label_input2);
  gtk_label_set_use_markup (GTK_LABEL (label_input2), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_cancel);
  GTK_WIDGET_SET_FLAGS (button_cancel, GTK_CAN_DEFAULT);

  button_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_ok);
  GTK_WIDGET_SET_FLAGS (button_ok, GTK_CAN_DEFAULT);

  statusbar_gdbfdiff = gtk_statusbar_new ();
  gtk_widget_show (statusbar_gdbfdiff);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar_gdbfdiff, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) quit_giconv, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) about_giconv, "activate",
                    G_CALLBACK (on_about_giconv_activate),
                    NULL);
  g_signal_connect ((gpointer) filechooserbutton_input1, "realize",
                    G_CALLBACK (on_filechooserbutton_input1_realize),
                    NULL);
  g_signal_connect ((gpointer) filechooserbutton_input2, "realize",
                    G_CALLBACK (on_filechooserbutton_input2_realize),
                    NULL);
  g_signal_connect_swapped ((gpointer) button_cancel, "clicked",
                            G_CALLBACK (gtk_main_quit),
                            GTK_OBJECT (window_gdbfdiff));
  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gdbfdiff, window_gdbfdiff, "window_gdbfdiff");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, quit_giconv, "quit_giconv");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, about_giconv, "about_giconv");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, frame_input, "frame_input");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, filechooserbutton_input1, "filechooserbutton_input1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, label_input, "label_input");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, filechooserbutton_input2, "filechooserbutton_input2");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, label_input2, "label_input2");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window_gdbfdiff, statusbar_gdbfdiff, "statusbar_gdbfdiff");

  gtk_window_add_accel_group (GTK_WINDOW (window_gdbfdiff), accel_group);

  return window_gdbfdiff;
}

GtkWidget*
create_aboutdialog_gdbfdiff (void)
{
  GtkWidget *aboutdialog_gdbfdiff;
  const gchar *authors[] = {
    "Steffen Macke <Steffen_Macke@dorsch.com.jo>",
    "Maher Abdel Karim <Maher_Karim@dorsch.com.jo>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  aboutdialog_gdbfdiff = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), _("gdbfdiff"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), _("Copyright (c) 2006 DC Water and Enviroment"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), _("Compare the structure of two DBF files."));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), _("gdbfdiff - Compare the structure of two DBF files.\n    Copyright (C) 2006  DC Water and Environment\n\n    This program is free software; you can redistribute it and/or modify\n    it under the terms of the GNU General Public License as published by\n    the Free Software Foundation; either version 2 of the License, or\n    (at your option) any later version.\n\n    This program is distributed in the hope that it will be useful,\n    but WITHOUT ANY WARRANTY; without even the implied warranty of\n    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n    GNU General Public License for more details.\n\n    You should have received a copy of the GNU General Public License\n    along with this program; if not, write to the Free Software\n    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA"));
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), "http://dcwaterdesign.sourceforge.net");
  gtk_about_dialog_set_website_label (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), _("http://dcwaterdesign.sourceforge.net"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog_gdbfdiff), translators);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog_gdbfdiff, aboutdialog_gdbfdiff, "aboutdialog_gdbfdiff");

  return aboutdialog_gdbfdiff;
}

