;;
;; Windows GSHPVORONOI NSIS installer language macros
;;

!macro GSHPVORONOI_MACRO_DEFAULT_STRING LABEL VALUE
  !ifndef "${LABEL}"
    !define "${LABEL}" "${VALUE}"
    !ifdef INSERT_DEFAULT
      !warning "${LANG} lang file mising ${LABEL}, using default.."
    !endif
  !endif
!macroend

!macro GSHPVORONOI_MACRO_LANGSTRING_INSERT LABEL LANG
  LangString "${LABEL}" "${LANG_${LANG}}" "${${LABEL}}"
  !undef "${LABEL}"
!macroend

!macro GSHPVORONOI_MACRO_LANGUAGEFILE_BEGIN LANG
  !define CUR_LANG "${LANG}"
!macroend

!macro GSHPVORONOI_MACRO_LANGUAGEFILE_END
  !define INSERT_DEFAULT
  !include "${GSHPVORONOI_DEFAULT_LANGFILE}"
  !undef INSERT_DEFAULT

  ; GSHPVORONOI Language file Version 2
  ; String labels should match those from the default language file.
  
  ; .onInit checks
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_NO_GTK				${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_NO_INSTALL_OVER			${CUR_LANG}

  ; License Page
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_LICENSE_BUTTON			${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_LICENSE_BOTTOM_TEXT		${CUR_LANG}

  ; Components Page
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_SECTION_TITLE			${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_SECTION_DESCRIPTION		${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT TRANSLATIONS_SECTION_TITLE		${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT TRANSLATIONS_SECTION_DESCRIPTION	${CUR_LANG}
  
  ; Installer Finish Page
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_FINISH_VISIT_WEB_SITE		${CUR_LANG}

  ; GSHPVORONOI Section Prompts and Texts
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_UNINSTALL_DESC			${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_PROMPT_WIPEOUT			${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT GSHPVORONOI_PROMPT_DIR_EXISTS		${CUR_LANG}

  ; Uninstall Section Prompts
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT un.GSHPVORONOI_UNINSTALL_ERROR_1		${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT un.GSHPVORONOI_UNINSTALL_ERROR_2		${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT un.GSHPVORONOI_UNINSTALLATION_WARNING	${CUR_LANG}
  !insertmacro GSHPVORONOI_MACRO_LANGSTRING_INSERT un.GSHPVORONOI_DOTGSHPVORONOI_WARNING		${CUR_LANG}

  !undef CUR_LANG
!macroend

!macro GSHPVORONOI_MACRO_INCLUDE_LANGFILE LANG FILE
  !insertmacro GSHPVORONOI_MACRO_LANGUAGEFILE_BEGIN "${LANG}"
  !include "${FILE}"
  !insertmacro GSHPVORONOI_MACRO_LANGUAGEFILE_END
!macroend
