/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window_gshpvoronoi (void)
{
  GtkWidget *window_gshpvoronoi;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem1;
  GtkWidget *menuitem1_menu;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit_gshpvoronoi;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *help_gshpvoronoi;
  GtkWidget *separator1;
  GtkWidget *about_gshpvoronoi;
  GtkWidget *frame_input;
  GtkWidget *alignment2;
  GtkWidget *filechooserbutton_input;
  GtkWidget *label_input;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *filechooserwidget_output;
  GtkWidget *label_output;
  GtkWidget *hbuttonbox1;
  GtkWidget *button_cancel;
  GtkWidget *button_ok;
  GtkWidget *statusbar_gshpvoronoi;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_gshpvoronoi = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_gshpvoronoi), _("gshpvoronoi"));
  gtk_window_set_icon_name (GTK_WINDOW (window_gshpvoronoi), "gtk-execute");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_gshpvoronoi), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem1);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem1);

  menuitem1_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit_gshpvoronoi = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit_gshpvoronoi);
  gtk_container_add (GTK_CONTAINER (menuitem1_menu), quit_gshpvoronoi);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  help_gshpvoronoi = gtk_image_menu_item_new_from_stock ("gtk-help", accel_group);
  gtk_widget_show (help_gshpvoronoi);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), help_gshpvoronoi);

  separator1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  about_gshpvoronoi = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about_gshpvoronoi);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), about_gshpvoronoi);

  frame_input = gtk_frame_new (NULL);
  gtk_widget_show (frame_input);
  gtk_box_pack_start (GTK_BOX (vbox1), frame_input, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame_input), 4);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame_input), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  filechooserbutton_input = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton_input);
  gtk_container_add (GTK_CONTAINER (alignment2), filechooserbutton_input);

  label_input = gtk_label_new (_("<b>Input</b>"));
  gtk_widget_show (label_input);
  gtk_frame_set_label_widget (GTK_FRAME (frame_input), label_input);
  gtk_label_set_use_markup (GTK_LABEL (label_input), TRUE);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox1), frame1, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame1), 4);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  filechooserwidget_output = gtk_file_chooser_widget_new (GTK_FILE_CHOOSER_ACTION_SAVE);
  gtk_widget_show (filechooserwidget_output);
  gtk_container_add (GTK_CONTAINER (alignment1), filechooserwidget_output);

  label_output = gtk_label_new (_("<b>Output</b>"));
  gtk_widget_show (label_output);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label_output);
  gtk_label_set_use_markup (GTK_LABEL (label_output), TRUE);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbuttonbox1, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_END);

  button_cancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_cancel);
  GTK_WIDGET_SET_FLAGS (button_cancel, GTK_CAN_DEFAULT);

  button_ok = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (button_ok);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), button_ok);
  GTK_WIDGET_SET_FLAGS (button_ok, GTK_CAN_DEFAULT);

  statusbar_gshpvoronoi = gtk_statusbar_new ();
  gtk_widget_show (statusbar_gshpvoronoi);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar_gshpvoronoi, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) quit_gshpvoronoi, "activate",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) help_gshpvoronoi, "activate",
                    G_CALLBACK (on_help_gshpvoronoi_activate),
                    NULL);
  g_signal_connect ((gpointer) about_gshpvoronoi, "activate",
                    G_CALLBACK (on_about_gshpvoronoi_activate),
                    NULL);
  g_signal_connect ((gpointer) filechooserbutton_input, "realize",
                    G_CALLBACK (on_filechooserbutton_input_realize),
                    NULL);
  g_signal_connect_swapped ((gpointer) button_cancel, "clicked",
                            G_CALLBACK (gtk_main_quit),
                            GTK_OBJECT (window_gshpvoronoi));
  g_signal_connect ((gpointer) button_ok, "clicked",
                    G_CALLBACK (on_button_ok_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_gshpvoronoi, window_gshpvoronoi, "window_gshpvoronoi");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, menuitem1, "menuitem1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, menuitem1_menu, "menuitem1_menu");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, quit_gshpvoronoi, "quit_gshpvoronoi");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, help_gshpvoronoi, "help_gshpvoronoi");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, separator1, "separator1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, about_gshpvoronoi, "about_gshpvoronoi");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, frame_input, "frame_input");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, filechooserbutton_input, "filechooserbutton_input");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, label_input, "label_input");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, filechooserwidget_output, "filechooserwidget_output");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, label_output, "label_output");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, button_ok, "button_ok");
  GLADE_HOOKUP_OBJECT (window_gshpvoronoi, statusbar_gshpvoronoi, "statusbar_gshpvoronoi");

  gtk_window_add_accel_group (GTK_WINDOW (window_gshpvoronoi), accel_group);

  return window_gshpvoronoi;
}

GtkWidget*
create_aboutdialog_gshpvoronoi (void)
{
  GtkWidget *aboutdialog_gshpvoronoi;
  const gchar *authors[] = {
    "Steffen Macke <Steffen_Macke@dorsch.com.jo>",
    "Maher Abdel Karim <Maher_Karim@dorsch.com.jo>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GdkPixbuf *aboutdialog_gshpvoronoi_logo_pixbuf;

  aboutdialog_gshpvoronoi = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), _("gshpvoronoi"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), _("Copyright (c) 2006 DC Water and Enviroment"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), _("Create Voronoi polygons from point shapfiles.\nGraphical frontend to qvoronoi."));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), _(" gshpvoronoi - Create Voronoi polygons from point shapefiles Graphical frontend to qvoronoi\n    Copyright (C) 2006  DC Water and Environment\n\n    This program is free software; you can redistribute it and/or modify\n    it under the terms of the GNU General Public License as published by\n    the Free Software Foundation; either version 2 of the License, or\n    (at your option) any later version.\n\n    This program is distributed in the hope that it will be useful,\n    but WITHOUT ANY WARRANTY; without even the implied warranty of\n    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n    GNU General Public License for more details.\n\n    You should have received a copy of the GNU General Public License\n    along with this program; if not, write to the Free Software\n    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA"));
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), "http://dcwaterdesign.sourceforge.net");
  gtk_about_dialog_set_website_label (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), _("http://dcwaterdesign.sourceforge.net"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), translators);
  aboutdialog_gshpvoronoi_logo_pixbuf = create_pixbuf ("dc.png");
  gtk_about_dialog_set_logo (GTK_ABOUT_DIALOG (aboutdialog_gshpvoronoi), aboutdialog_gshpvoronoi_logo_pixbuf);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog_gshpvoronoi, aboutdialog_gshpvoronoi, "aboutdialog_gshpvoronoi");

  return aboutdialog_gshpvoronoi;
}

